// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMyNapdWu1gG9Jl5oR9lSeGQeSqTBEsfs',
    appId: '1:743416464980:web:5c756c90ac1398f0f5cfc1',
    messagingSenderId: '743416464980',
    projectId: 'execai-with-host',
    authDomain: 'execai-with-host.firebaseapp.com',
    storageBucket: 'execai-with-host.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMCHimqtpWnVAJxWnZCp30zkGqZFA3-H8',
    appId: '1:743416464980:android:ba0d875c5808f2d3f5cfc1',
    messagingSenderId: '743416464980',
    projectId: 'execai-with-host',
    storageBucket: 'execai-with-host.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMyNapdWu1gG9Jl5oR9lSeGQeSqTBEsfs',
    appId: '1:743416464980:web:c4266ee616f7e48bf5cfc1',
    messagingSenderId: '743416464980',
    projectId: 'execai-with-host',
    authDomain: 'execai-with-host.firebaseapp.com',
    storageBucket: 'execai-with-host.firebasestorage.app',
  );
}
